services:
  - type: web
    name: oncoreconcile-api
    runtime: docker
    plan: free
    rootDir: .
    dockerfilePath: ./backend/Dockerfile.render
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: ALLOWED_ORIGINS
        sync: false
